package com.entrypoints.endpointsvariables.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class AutoGeneratedController {
	
	@Autowired
	private IDelegate delegate;

	@RequestMapping(path = "/api/v1/entrypoint", method = RequestMethod.GET)
	public String controllerMethod() {
		return this.delegate.controllerMethod();
	}
	
}
